name: crypto_app
description: "A crypto app showcasing how to use pine bricks."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  auto_route: ^7.8.4
  cached_network_image: ^3.3.1
  dio: ^5.4.0
  dio_smart_retry: ^6.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_essentials_kit: ^2.5.0
  freezed_annotation: ^2.4.1
  intl: ^0.18.1
  json_annotation: ^4.8.1
  pine: ^1.0.3
  provider: ^6.1.1
  retrofit: ^4.1.0
  talker: ^4.0.1
  talker_bloc_logger: ^4.0.1
  talker_dio_logger: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^7.3.2
  bloc_test: ^9.1.5
  build_runner: ^2.4.8
  data_fixture_dart: ^2.2.0
  flutter_lints: ^3.0.1
  freezed: ^2.4.7
  http_mock_adapter: ^0.6.1
  json_serializable: ^6.7.1
  mockito: ^5.4.4
  retrofit_generator: ^8.1.0
flutter:
  uses-material-design: true
